### ISSUE TITLE
Create select exercise page for patient

### ISSUE THREAD

**Issue by shreyapandit** [ExerciseCheck/server#16]
- [ ] Query reference exercise for that patient to see which reference exercise and how many sessions are requested. The reference exercises need to be rendered as a list on the UI.
- [ ] Now, Query practice model and see how many practice exercises are done for that reference. 
- [ ]  Enhance current user local storage object (patient) with selected exercise information above. Reference id, total_repetitions, completed_repetitions to be saved to local storage
 Also Redirect to #26 

Can reuse a potential ui template from #8 

[Related Mockup Screen](https://xd.adobe.com/view/9da22e05-1860-4a03-918f-fa7e119d7b89/screen/1b03730b-a90e-4460-8255-4db1014d63db/Clinician-Select-Exercise)

**Comment by asadeg02** [comment]
in the mock-Up created by San, Does the patient see the number of sessions for the reference exercise ?

**Comment by shreyapandit** [comment]
Not on this page @asadeg02

**Comment by sktran** [comment]
@asadeg02 This page will serve as a place for patients to select the exercise to perform. Information about the exercise, the number of reps and sets, and other details will be stored on other pages (to be discussed). We know for certain that the patient will see the number of reps and sets for each exercise after selecting it (e.g., [on the exercise screen](https://xd.adobe.com/view/9da22e05-1860-4a03-918f-fa7e119d7b89/screen/147384e8-b457-46e5-a9ff-d7322cc1a01a/Exercise-Portal-Start-S1)).
